name: gary petersen
favicon: null
layout_spectrum: 0.051663346122950315
typography_spectrum: 0.08972491533495486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.49866919382475317
  lightness: 0.988516345154494
  saturation: 0.18466297909617424
  rhythmicContrast: 0.6018965835683048
purpose: []
